---
title: "Xuan's awesome website"
output: 
  html_document:
    theme: cerulean
---

# This is Xuan's resume
This website is coded by Xuan using to perform academic and professional experience.

Go back to [homepage](index.html)

I am Yaxuan Zheng, an international student from China. 

I was a dedicated and accomplished Financial Mathematics student at Xi'an Jiaotong Liverpool University, with an expected graduation in July 2025. Throughout their academic journey, they have maintained an average score of 73/100 and a GPA of 3.63, earning the University Academic Achievement Award for the 2022/2023 academic year. 
Now I am student in Columbia Mailman School of MS biostatistics program, Public Health Data Science track. 
My academic interests lie at the intersection of biostatistics, data science, and public health research, where I aim to apply quantitative methods to understand complex health and environmental relationships.

I have gained practical experience through internships at prestigious institutions such as the Yangtze River Delta Digital Finance Institute, where they analyzed digital RMB usage, and AIA Group Limited, where they established risk monitoring models. 

My research experience has focused on statistical modeling and data-driven health analysis. In my recent project at the University of Michigan, I explored how long-term exposure to PM2.5 and low-grade inflammation interact to affect brain health using data from over 31,000 participants in the UK Biobank. I also investigated the effect of gastric lavage on survival outcomes following poisoning, applying Kaplan–Meier estimation and Cox proportional hazards models to clinical data. Currently, I am conducting an integrated survival analysis on Type 2 Diabetes using national survey data to identify key behavioral and metabolic risk factors.

Through these projects, I’ve developed strong skills in R programming, data visualization, and survival analysis, along with a deep appreciation for how statistical reasoning can inform real-world health decisions. Looking ahead, I hope to continue exploring how data science can be used to promote population health and evidence-based policy.